### ISSUE TITLE
GRCh38 reference files

### ISSUE THREAD

**Issue by StefanoLise** [Wedge-lab/battenberg#100]
Hello, 

I would like to run Battenberg on some matched tumor/germline bam files, mapped on hg38. 

I have download the GRCh38 reference files from https://ora.ox.ac.uk/objects/uuid:08e24957-7e76-438a-bd38-66c48008cf52 as advised. I understand this should be a zip file but when I try to unzip it I get the following error

> unzip Battenberg_reference_hg38.zip 
Archive:  Battenberg_reference_hg38.zip
warning [Battenberg_reference_hg38.zip]:  29511068584 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [Battenberg_reference_hg38.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)

Could you please advise? Many thanks for your help. 

Kind regards,
Stefano

**Comment by StefanoLise** [comment]
Dear Julio Cesar,

thanks for your reply. I have tried downloading it to my laptop and directly to our HPC cluster (through wget). I get the same error message in both cases ... 

BW,
Stefano

**Comment by jcesar101** [comment]
Thank you Stefano, I'm sorry to hear that trying the download on a different computer didn't work. I have asked ORA about splitting the ZIP file into smaller files, but they are rather aiming to improve their service for downloading large files like these. In the meantime, their recommendation was to try one of the many free download manager services available in internet. Hopefully that will help.

**Comment by StefanoLise** [comment]
Thanks, would you be able to send me the MD5 checksums of the zipped file? Just to double check if the problem is with the download

**Comment by jcesar101** [comment]
Absolutely Stefano, please find following the MD5 checksum for the large zip file: 0a813d95fe54c615f7d5fa371f35a5d8

And the SHA1 checksums for the individual zip files that it contains:

af8b122ec0c6c7402071e59d334fa9129d563b4f  1000G_loci_hg38_chr.zip
a7ef3ae72f0ceb3bd90624f199ce875903ab8917  1000G_loci_hg38.zip
330cc83b657a2d8ab8db450c1ae2509a4e7a1665  beagle_chr.zip
8869e7cca76a77ee36c5436e99d480e57fcba377  beagle.zip
929e6a4742bc49a8ed10fa9915c2fdb33f9e6887  chromosome_coordinates_hg38_chr.txt
16db62701eb8f107d6330c7720a13a1b3d16640a  chromosome_coordinates_hg38.txt
a06b838ccfb915a6ad02a3b14b259c3bea48baed  GC_correction_hg38_chr.zip
2af5e7700d8bd7f44ad3da1f10d238be2ccaebba  GC_correction_hg38.zip
c2cc5417f4884bca3ea17feb0f8d76e390698680  imputation_chr.zip
7f035e3e3f666020dd5f72ee3aef555a4bec6d46  imputation.zip
b1363427eeb71d55c68233d9f1a6fab451047343  probloci_chr.zip
d1ca31100969a37b579e7d05306f76ff42e98e05  probloci.zip
c5e5e7d43a28d77f9ee9a53b0a806817fc4bfff4  README.txt
9cae8cc0e8219eac3eb91ec342c536aad3f3e777  RT_correction_hg38_chr.zip
79f5ef7cb3d92967eb0baa6100113568ea48a5ac  RT_correction_hg38.zip
1dcbeb21a765abb8b04f42430001489ac7a0b90b  shapeit2_chr.zip
793b03872c0271d6a80a4b86d7996974f8947ff2  shapeit2.zip

I hope this helps.

**Comment by StefanoLise** [comment]
Hi, 

I have managed to extract the files from the large zip file, it seems the problem was with the 'unzip' command that was giving an error message. Instead unzipping with 7zip worked OK (https://7-zip.org/download.html).  The SHA1 checksums for the individual extracted files match what you have provided. Hope this is of help to others too.
