### ISSUE TITLE
Does it fit for shallow WGS data?

### ISSUE THREAD

**Issue by WangKang-Leo** [Wedge-lab/battenberg#104]
I have a question on the input of battenberg. We have sWGS data, with read depth 0.3X. Do you recommend to run battenberg? Moreover, we have tumor-normal paied WES data for those samples, can I call allele specific CNA jointly using sWGS and WES data together?

**Comment by davidwedge** [comment]
Battenberg requires b-allele- frequencies as well as sequencing depths. It is not therefore possible to run Battenberg on shallow WGS.
We do not currently have a version of Battenberg that works on WES. However, we are working on this and hope to have a release version ready before the end of the year.
