### ISSUE TITLE
Reference Files for hg38

### ISSUE THREAD

**Issue by ssrinivasan2** [Wedge-lab/battenberg#105]
Hi,

Could you please let me know where I can find the problem loci, imputation, GC correction and RT files for hg38?

The instructions on Github list that these files should in the Oxford Archive repository (link below), but the only file available for download is Battenberg_reference_hg38.zip.

Could you please let me know where I can find the other required files for hg38?

Thanks so much!

Oxford Archive for hg38:
https://ora.ox.ac.uk/objects/uuid:08e24957-7e76-438a-bd38-66c48008cf52

**Comment by jcesar101** [comment]
Hi,

all those reference files are inside the compressed ZIP file available at ORA (link already provided). The current file format was a recommendation from ORA.


Best regards.
