### ISSUE TITLE
Battenberg on whole Exome sequencing?

### ISSUE THREAD

**Issue by shaghayeghsoudi** [Wedge-lab/battenberg#110]
Hi, 
I just wanted a quick question, can We run Battenberg on whole Exome sequencing?
Thanks

**Comment by lincj1994** [comment]
Hi. Same question. 
If battenberg works on WES data, could you please provide a tutorial or an example?

**Comment by davidwedge** [comment]
Currently, Battenberg doesn't run on WES data. However, we are working on a version of Battenberg that will do this. The expected release date is early in 2024.

**Comment by lincj1994** [comment]
Hi. Thank you for reply. Can I run Battenberg on ASCAT output?

**Comment by becky-genomics** [comment]
Hi David, I was wondering if you are still planning on releasing a version for WES data? Many thanks :)

**Comment by ANImaL-AV9** [comment]
Hi @davidwedge, May I know any update about Battenberg version on WES data?
