### ISSUE TITLE
Error in prepare_wgs_cell_line while running battenberg on wgs data 

### ISSUE THREAD

**Issue by parth2608** [Wedge-lab/battenberg#113]
I get the following error while running battenberg on my wgs bam files in R 4.1.0

Error in `$<-.data.frame`(`*tmp*`, "Position2", value = c(NA_real_, NA_real_ : 
  replacement has 2 rows, data has 0
Calls: battenberg ... prepare_wgs_cell_line -> cell_line_baf_logR -> $<- -> $<-.data.frame
Execution halted

I am not sure how to resolve the issue. Any assistance will be helpful.
Thank you!

Below is the entire output log file:

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13" "14" "15"
[16] "16" "17" "18" "19" "20" "21" "22"
Reading locis
Reading locis
Reading locis
Reading locis
Reading locis
Reading locis
Reading locis
Reading locis
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Reading locis
Reading locis
Done reading locis
Multi pos start:
Reading locis
Reading locis
Reading locis
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Reading locis
Reading locis
Done reading locis
Multi pos start:
Reading locis
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Reading locis
Reading locis
Done reading locis
Multi pos start:
Reading locis
Reading locis
Reading locis
Reading locis
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
Done reading locis
Multi pos start:
[1] 1
[1] 1
Error in `$<-.data.frame`(`*tmp*`, "Position2", value = c(NA_real_, NA_real_ : 
  replacement has 2 rows, data has 0
Calls: battenberg ... prepare_wgs_cell_line -> cell_line_baf_logR -> $<- -> $<-.data.frame
Execution halted

**Comment by jcesar101** [comment]
Hi,

could you please provide the script used to launch this execution of Battenberg, and also, what version (tag or branch) are you currently using?

Thank you.

**Comment by parth2608** [comment]
Hi, 

Thank you for getting back promptly.

I am using the master branch. I have attached the modified battenberg_wgs.R script and the lsf job script that use run battenberg.

[battenberg_wgs_traction2.txt](https://github.com/Wedge-lab/battenberg/files/13044428/battenberg_wgs_traction2.txt)
[battenberg_job.txt](https://github.com/Wedge-lab/battenberg/files/13044436/battenberg_job.txt)

Thank you.

**Comment by jcesar101** [comment]
Hi,

thank you for your reply. We are in the process of preparing a new release, and most of the corrections for the new modes (including cell_line mode) are still in the dev branch, could you please try using the version in that branch instead and let me know the outcome?

Also, could you please confirm where did you get the reference files you are currently using?


Thank you.

**Comment by parth2608** [comment]
Hi, 

I will try to run this using the new dev branch, and update you as soon as possible. I am not sure from where the reference files that I use have been sourced, but I am in the process of using the reference files from: https://ora.ox.ac.uk/objects/uuid:08e24957-7e76-438a-bd38-66c48008cf52

Thank you.

**Comment by parth2608** [comment]
Hi, 

I did use the dev branch version, but I still face the same error:

Error in `$<-.data.frame`(`*tmp*`, "Position2", value = c(NA_real_, NA_real_ : 
  replacement has 2 rows, data has 0
Calls: battenberg ... prepare_wgs_cell_line -> cell_line_baf_logR -> $<- -> $<-.data.frame
Execution halted

Also, I am using the reference files provided by ORA.

Here are my scripts and log file

[battenberg_job.txt](https://github.com/Wedge-lab/battenberg/files/13057314/battenberg_job.txt)
[battenberg_log.txt](https://github.com/Wedge-lab/battenberg/files/13057315/battenberg_log.txt)
[battenberg_wgs.txt](https://github.com/Wedge-lab/battenberg/files/13057316/battenberg_wgs.txt)

Thank you.

**Comment by GuyuanTang** [comment]
Hi, I also have the same issue. And when I try to figure it out, it seems that after this filter:
```
ohet=o[which(o$baf>=0.10 & o$baf<=0.90 & o$depth>10),]
```
I only got one row. So it produced the error. I think it is because of the filter on `depth`, but how can it be solved? Thank you so much!

**Comment by a3schiller** [comment]
Hi!

I have the same issue. Did you manage to solve it @parth2608 and @GuyuanTang?

Thanks in advance!

**Comment by nansari-pour** [comment]
Thank you for bringing this to our attention. Below is a fix for this issue, reasons for this observation, and a cautionary note:

**a) fix**

Replace:

```
ohet$Position2=c(ohet$Position[2:nrow(ohet)],2*ohet$Position[nrow(ohet)]-ohet$Position[nrow(ohet)-1])
ohet$Position_dist=ohet$Position2-ohet$Position
ohet$Position_dist_percent=ohet$Position_dist/max(ohet$Position_dist)
```

with:

```
if (nrow(ohet)<2){
      print(paste("Number of hetSNPs below 2 for the entire chromosome",chr,"- no IVD calculation; assuming chrom-length LOH"))
      ohet=0
    } else {
    ohet$Position2=c(ohet$Position[2:nrow(ohet)],2*ohet$Position[nrow(ohet)]-ohet$Position[nrow(ohet)-1])
    ohet$Position_dist=ohet$Position2-ohet$Position
    ohet$Position_dist_percent=ohet$Position_dist/max(ohet$Position_dist)
    }
```

_This fix will be added as part of the new release (coming soon)._

**b) possible scenarios leading to this observation**

There are two possible scenarios leading to this:

1) There is a full-length LOH in that chromosome with very little noise in BAF and therefore no or very few (<=2) hetSNPs with BAF in 0.1-0.9 are observed across the entire chromosome.  If this is the case, it actually shows you have a good WGS sample and with the current fix, it should work nicely.

2) The WGS quality is low and therefore the number of reads at given 1000G SNP loci tend to be lower than the minCount of 10 (i.e. depth). This leads to the exclusion of many hetSNPs even though their BAF falls within 0.1-0.9, not allowing to distinguish between a genuine LOH and noise from a bad quality sample.

**c) cautionary note** 

We do not recommend running the WGS cell-line mode  (or any other mode for that matter) with <30X depth. Even with the above fix, you may get spurious results and the output needs to be QCed.

**Comment by wangc90** [comment]
Hi @nansari-pour, thanks for publishing the new version.  However, after fixing the issue above by replacing these few lines, I run into another error with the current battenberg (V3.0) for cell line mode (based on the printout, the error seems to be generated after STEP 1). Can you help to fix that or point to the potential reason for this error:

<img width="1010" height="714" alt="Image" src="https://github.com/user-attachments/assets/e2f2a4a2-4244-4dc8-81af-26a7cfd22b3d" />


<img width="1010" height="852" alt="Image" src="https://github.com/user-attachments/assets/4748fe1e-a044-44bd-a4db-b4df6f21b813" />

**Comment by nansari-pour** [comment]
Hi @wangc90 
Based on your output, the pipeline is crashing after the first step because there is no coverage in the sequencing data and therefore baf is NaN. Start of chromosome 1 should always have good coverage across the targeted SNP loci e.g. see head of chr1 alleleFrequencies file for my latest run:

#CHR    POS     Count_A Count_C Count_G Count_T Good_depth
1       16103   0       0       0       104     104
1       51479   0       0       0       89      89
1       51898   0       77      0       0       77
1       51928   0       0       72      1       73
1       54490   0       0       93      0       93
1       54708   0       0       99      0       99

 This is likely due to a mismatch of genomebuild and reference files, looking at the wrong alleles, leading to coverage of 0, which is then crashing the subsequent step with the "$ operator" error. Please check the input count files that are being read by the tumour_only_baf_logR function.

The fact that you have <2 hetSNPs across the entire chr22 (previously discussed above) is also a red flag re how the input has been generated.

**Comment by wangc90** [comment]
> Hi [@wangc90](https://github.com/wangc90) Based on your output, the pipeline is crashing after the first step because there is no coverage in the sequencing data and therefore baf is NaN. Start of chromosome 1 should always have good coverage across the targeted SNP loci e.g. see head of chr1 alleleFrequencies file for my latest run:
> 
> #CHR POS Count_A Count_C Count_G Count_T Good_depth 1 16103 0 0 0 104 104 1 51479 0 0 0 89 89 1 51898 0 77 0 0 77 1 51928 0 0 72 1 73 1 54490 0 0 93 0 93 1 54708 0 0 99 0 99
> 
> This is likely due to a mismatch of genomebuild and reference files, looking at the wrong alleles, leading to coverage of 0, which is then crashing the subsequent step with the "$ operator" error. Please check the input count files that are being read by the tumour_only_baf_logR function.
> 
> The fact that you have <2 hetSNPs across the entire chr22 (previously discussed above) is also a red flag re how the input has been generated.

Hi @nansari-pour,

Thanks for the help. I realigned the reads to the hg38 reference genome (removed the "chr" from the chromosome notation e.g., chr1 to 1) and rerun the battenberg cell line mode with the new bam, it now gives me the copy number results without any errors (It seems alleleCounter will output all 0s if the chromosome notation in bam is "chr#"). One thing I noticed that there is no results for the chromosome X (the cell line is a female sample), I am wondering if you can point me to the right direction if I want to get copy numbers for the sex chromosomes robustly. 

Thanks,
Chao
