### ISSUE TITLE
chrX_copynumber.txt file format

### ISSUE THREAD

**Issue by sahliatef** [Wedge-lab/battenberg#115]
https://github.com/Wedge-lab/battenberg/blob/1796d9da6e98353c6995b2f73db72812b80a4986/R/fitcopynumber.R#L1268

In this output file CN gains are flagged as "+ve" and CN loss as "-ve".
Also some rows have a value "no" in the column "CNA" while having a value "-ve" or "+ve" in the column "type" which contradictory.

The recomandation is to fix the format of this file or don't save it as an output.

**Comment by nansari-pour** [comment]
Those columns were intended for internal use during code development and QC, and have now been removed from the "_chrX_copynumber.txt" output file for users.
