### ISSUE TITLE
CNA calls in PAR regions

### ISSUE THREAD

**Issue by sahliatef** [Wedge-lab/battenberg#117]
https://github.com/Wedge-lab/battenberg/blob/1796d9da6e98353c6995b2f73db72812b80a4986/R/fitcopynumber.R#L1256

In the final output we need to consider wether to merge to CN calls in the PAR regions (from the initial run without running the function "callChrXsubclones") and in the non-PAR regions (from the function "callChrXsubclones").

**Comment by nansari-pour** [comment]
The function callChrXsubclones is only run for male genomes (which are hemizygous for chrX) and replaces the original CN calls with LogR-based segmentation output. The PAR regions are not exclusive to chrX (and shared with chrY) and therefore merging the outputs from non-male specific PAR and male-specific non-PAR would not be equivalent in terms of copy number. We therefore only report the non-PAR regions in the final output which is chrX-only by definition.
