### ISSUE TITLE
SV brps outside the LogR data range

### ISSUE THREAD

**Issue by sahliatef** [Wedge-lab/battenberg#118]
https://github.com/Wedge-lab/battenberg/blob/1796d9da6e98353c6995b2f73db72812b80a4986/R/fitcopynumber.R#L976

When SV brps are used as input, we see cases where the SV brp positions are outside the range of the LogR data which lead the execution of the code to stop.

This can be fixed by replacing this code line with the following two code lines

svpos=sv[which((sv$pos > min(PCFinput$Position)) & (sv$pos < max(PCFinput$Position))),"pos"]
breakpoints=c(min(PCFinput$Position),svpos,max(PCFinput$Position))

**Comment by nansari-pour** [comment]
This is now fixed.
