### ISSUE TITLE
chrX SV brp check

### ISSUE THREAD

**Issue by sahliatef** [Wedge-lab/battenberg#119]
https://github.com/Wedge-lab/battenberg/blob/1796d9da6e98353c6995b2f73db72812b80a4986/R/fitcopynumber.R#L975

While importing the coordonates of SV brps from the SV input file, a check should be included to make sure that there is SV brps on chrX (there are situations where SV brps are called on autosomes but not chrX) otherwise the run failes.

**Comment by nansari-pour** [comment]
This is now fixed by checking the nrow of 'sv'.
