### ISSUE TITLE
Using telemer-to-telemer build

### ISSUE THREAD

**Issue by Ximelele** [Wedge-lab/battenberg#121]
Are you planning to add telemer-to-telemer build into Battenberg in near future? 

Or is there any chance of running it with lift-over data references? It would be very helpful if it was possible due to the fact that all our datasets very lift-overed to T2T.

**Comment by davidwedge** [comment]
Hi Martin, Thanks for the suggestion. Battenberg gets much of its power from the phasing of SNPs using a panel of genomes (the 1000 genomes). If such a panel becomes available aligned to T2T at some point, we would certainly consider this. Currently the best option is to liftover the SNP positions between T2T and GrCH38.
