### ISSUE TITLE
Battenberg_hg38.zip unzip failed

### ISSUE THREAD

**Issue by sunnaa0423** [Wedge-lab/battenberg#122]
Hi，there
   I've downloaded the Battenberg_hg38.zip so many times. Although I can successfully download the entire file and the downloaded data size appears to be correct, I consistently encounter failures during the decompression process. The error message suggests that the file may be corrupted. Is there an alternative way to download this file?
The following is the error message prompted during the unzip of the file.
Many thanks 

=========================================================================================
warning [Battenberg_hg38.zip]: 29511068584 extra bytes at beginning or within zipfile
(attempting to process anyway)
error [Battenberg_hg38.zip]: start of central directory not found;
zipfile corrupt.
(please check that you have transferred or created the zipfile in the
appropriate BINARY mode and that you have compiled UnZip properly)

**Comment by Ximelele** [comment]
Hello this issue was mentioned here couple of times. The issue is if you are using classic unzip which is size limited. Best solution is to use 7z.

**Comment by sunnaa0423** [comment]
> Hello this issue was mentioned here couple of times. The issue is if you are using classic unzip which is size limited. Best solution is to use 7z.

Thank you very much. I have tried it. Although there are error messages as below after decompression, the SHA-1 checksums generated for each file match those provided in sha1sums.txt.

====================================================================================
Scanning the drive for archives:
1 file, 33806037315 bytes (32 GiB)

Extracting archive: rt435gd52w

ERRORS:
Headers Error

--
Path = rt435gd52w
Type = zip
ERRORS:
Headers Error
Physical Size = 33806037315
64-bit = +

                                    

Archives with Errors: 1

Open Errors: 1

**Comment by jcesar101** [comment]
Hi,

if the checksums of the extracted files match those provided, then the decompression should be fine, and the "Headers Error" might be unrelated. Could you please confirm if this is the case?

As mentioned in a previous post, for large zip files the best option is to use a recent unzip version (or other tool such as 7-zip) and decompress these files in a 64-bit platform.

Kind regards.
