### ISSUE TITLE
sh: alleleCounter: command not found

### ISSUE THREAD

**Issue by fswirsky** [Wedge-lab/battenberg#124]
Hi,

I'm trying to run the battenberg() function on some BAM files I have and keep getting this error
`sh: alleleCounter: command not found`

Any help is greatly appreciated

**Comment by jcesar101** [comment]
Hi,

thank you for using battenberg. The alleleCounter is an external tool used by the pipeline and should be installed into and available from the environment where the pipeline is invoked. If not currently installed, the tool can be downloaded from: https://github.com/cancerit/alleleCount

Kind regards.
