### ISSUE TITLE
chr prefix AND beagle failed

### ISSUE THREAD

**Issue by zxx0902** [Wedge-lab/battenberg#128]
Hi
Recently,I'm using Battenberg and facing some situation I seriously can't cope with, so I need your help.
My question：
1. i have some question about parameters. Could you tell me if  there are any wrong changes?
I used the inst/example/battenberg_wgs.R  with hg38 reference ending in "_chr."
I have change the code as follow:
BEAGLE_BASEDIR = "/my_path/Battenberg_reference_chr"

I remove the chr in following parameters. Due to running with default value,the program was halted with error message(can't find the file eg :1kg.phase3.v5a_GRCh38nounref_allele_index_chrchr1_).i think the change is right because i get BAF and LogR with no error message.

G1000ALLELESPREFIX = file.path（.../1kg.phase3.v5a_GRCh38nounref_allele_index_")
G1000LOCIPREFIX = file.path(.../1kg.phase3.v5a_GRCh38nounref_loci_")
GCCORRECTPREFIX = file.path(.../1000G_GC_")
REPLICCORRECTPREFIX = file.path(../1000G_RT_")
BEAGLEREF.template = file.path(../CHROMNAME.1kg.phase3.v5a_GRCh38nounref.vcf.gz")
BEAGLEPLINK.template = file.path(../plink.CHROMNAME.GRCh38.map"）
 BEAGLEJAR = file.path(../beagle.08Feb22.fa4.jar")
 CHROM_COORD_FILE =/my_path/chromosome_coordinates_hg38_chr.txt"

### my data are paired tumor and normal WGS files ,so I think i should use "paied".That is right? 
analysis = "paired"

Run the command:
$R_dir/Rscript $t_dir/battenberg_wgs.R -t ${sample_id} -n ${sample_id%_*}_0 --tb $tumor_bam --nb $Normal_bam --sex $gender -o $out_dir --cpu $threads
 name of result files inculdes "chrchr"  rather than "chr".for example: the 'tumourAlleleCountsFile.prefix' is designated in the source already include 'chr' inside .
2. i use all reference file with chr. why i get LC_141_3_impute_input_chrchr1.txt without "chr" ?
snp1 1:3727147 3727147 C T 1 0 0
snp2 1:3728241 3728241 A G 0 1 0
snp3 1:3728294 3728294 G C 1 0 0
snp4 1:3728313 3728313 A C 1 0 0
3:i use hg38 reference ,why i get head notion with GRCh37 in  LC_141_3_beagle5_input_chrchr1.txt?
##fileformat=VCFv4.2
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##reference=GRCh37
4：i don't know why i received this error message 
Command line: java -Xmx9813m -jar beagle.08Feb22.fa4.jar
  gt=LC_141_3_beagle5_input_chrchr2.txt
 ref=/my_path/chr2.1kg.phase3.v5a_GRCh38nounref.vcf.gz
  out=LC_141_3_beagle5_output_chrchr2.txt
  map=/my_path/plink.chr2.GRCh38.map
  nthreads=1
  window=40
  overlap=4
  impute=false
java.lang.IllegalArgumentException: No VCF records after filtering
        at vcf.WindowIt$Reader.run(WindowIt.java:246)
        at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalArgumentException: No VCF records after filtering
        at vcf.WindowIt$Reader.run(WindowIt.java:246)
        at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalArgumentException: No VCF records after filtering
        at vcf.WindowIt$Reader.run(WindowIt.java:246)
        at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalArgumentException: No VCF records after filtering
        at vcf.WindowIt$Reader.run(WindowIt.java:246)
        at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalArgumentException: No VCF records after filtering
        at vcf.WindowIt$Reader.run(WindowIt.java:246)
        at java.lang.Thread.run(Thread.java:748)
[Battenberg_LC_141_3.out.txt](https://github.com/Wedge-lab/battenberg/files/14646896/Battenberg_LC_141_3.out.txt)
[](https://github.com/Wedge-lab/battenberg/issues/127l)

**Comment by jcesar101** [comment]
Hi,

first of all thank you for using the Battenberg package. I'll try to help you with these problems.

1. The change is correct and the analysis type (-a) should be "paired".
2. These files should contain the chromosome names with the chr prefix. Could you please check the impute_info.txt on your environment, as this is where that information is retrieved from for this step.
3. Depending on the Battenberg version (or branch), the default value for the genome build is "hg19", you can explicitly set the required build with the command line parameter -g (or --ref_genome_build), e.g., -g hg38
4. Could you please check if the chromosome names in the generated vcf files contain the chr prefix or not? This might be related to the problems above, or to some other reference files not consistent with the rest in terms of the chr prefix

**Comment by zxx0902** [comment]
Hi
Firstly,Thanks for you suggestion and so quickly to reply my question.
Yestoday, i check all hg38 reference file form *_chr.zip. I found that chromosome name don't contain chr prefix in chrN.1kg.phase3.v5a_GRCh38nounref.vcf.gz of beagle. Then, i add the prefix to all file in chrN.1kg.phase3.v5a_GRCh38nounref.vcf.gz .So The second and fourth problem were solved.I can get corresponding file without error message. 

About question 3:
I think i set value of ref_genome_build to hg38  in battenberg_wgs. R.  the code as follow:

 library(Battenberg)
library(optparse)
........
****GENOMEBUILD = "hg38"****
USEBEAGLE = T
......
} else if (GENOMEBUILD=="hg38") {
        BEAGLE_BASEDIR = "/mypath/Battenberg_reference"
        GENOMEBUILD = "hg38"
        IMPUTEINFOFILE = file.path(BEAGLE_BASEDIR, "imputation/impute_info_1.txt")
        G1000ALLELESPREFIX = file.path(BEAGLE_BASEDIR, "1000G_loci_hg38/1kg.phase3.v5a_GRCh38nounref_allele_index_")
        G1000LOCIPREFIX = file.path(BEAGLE_BASEDIR, "1000G_loci_hg38/1kg.phase3.v5a_GRCh38nounref_loci_")
        GCCORRECTPREFIX = file.path(BEAGLE_BASEDIR, "GC_correction_hg38/1000G_GC_")
        REPLICCORRECTPREFIX = file.path(BEAGLE_BASEDIR, "RT_correction_hg38/1000G_RT_")
        PROBLEMLOCI = file.path(BEAGLE_BASEDIR, "probloci/probloci.txt.gz")

        BEAGLEREF.template = file.path(BEAGLE_BASEDIR, "beagle_chr/CHROMNAME.1kg.phase3.v5a_GRCh38nounref.vcf.gz")
        BEAGLEPLINK.template = file.path(BEAGLE_BASEDIR, "beagle_chr/plink.CHROMNAME.GRCh38.map")
        BEAGLEJAR = file.path(BEAGLE_BASEDIR, "beagle_chr/beagle.08Feb22.fa4.jar")

        CHROM_COORD_FILE = "/public/xxzhang/01.Project_LungCancer_WGS/02.Battenberg/Battenberg_reference/chromosome_coordinates_hg38_chr.txt"

If i use hg19 version,i think i will get the error message .eg. can't find battenberg_1000genomesloci2012_v3/1000genomesAlleles2012_chrN*. So i think i use the right reference version .  also get the same annotation with GRCh37 in the  LC_141_3_beagle5_input_chrchrN.txt

##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##reference=GRCh37
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SAMP001
chr1    3727147 .       C       T       .       PASS    .       GT      0/0
chr1    3728241 .       A       G       .       PASS    .       GT      0/1
chr1    3728294 .       G       C       .       PASS    .       GT      0/0

Do I need to make any other changes to files for beagle_chr.zip(dowmloaded form [https://ora.ox.ac.uk/objects/uuid :08e24957-7e76-438a-bd38-66c48008cf52]) ? or maybe I missed the some steps?

New question:
I get the warning message and i don't know if this affect to my results?
1: In diff(as.numeric(SNPpos[, 1])) : NAs introduced by coercion
2: The `path` argument of `write_tsv()` is deprecated as of readr 1.4.0.
ℹ Please use the `file` argument instead.
ℹ The deprecated feature was likely used in the Battenberg package.
  Please report the issue to the authors

[battenberg_wgs.R.txt](https://github.com/Wedge-lab/battenberg/files/14662947/battenberg_wgs.R.txt)
[Battenberg_LC_141_1.out.txt](https://github.com/Wedge-lab/battenberg/files/14662948/Battenberg_LC_141_1.out.txt)

**Comment by jcesar101** [comment]
Hi!,

regarding the incorrect reference in the *beagle5_input_* files, I checked that section of the code in detail, and is in fact keeping the default value for the reference genome build (hg19). This will be fixed in the next release of Battenberg, but it can be safely ignored as these are informative fields, unless you need sharing these intermediate files, in which case they should be edited to state the right genome build. No further changes are needed.

Regarding your new questions, both warning messages can be safely ignored. The new release of Battenberg will also include some changes to prevent these warnings from happening at the end.

**Comment by zxx0902** [comment]
Thanks for you help
