### ISSUE TITLE
Unclear error while running Battenberg from R

### ISSUE THREAD

**Issue by carinelegrand** [Wedge-lab/battenberg#129]
Hi,

I installed Battenberg via devtools, following the instructions here : https://github.com/Wedge-lab/battenberg. After installing all necessary dependencies and downloading-unzipping-linking the reference files (hg38, downloaded from https://ora.ox.ac.uk/objects/uuid:08e24957-7e76-438a-bd38-66c48008cf52), and making sure that all necessary executables are available on the PATH, I still run into the following, not entirely easy to decrypt, error message : 

"
 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13" "14" "15" "16" "17" "18" "19" "20" "21" "22" "X" 

Error in { : 
  task 1 failed - "'file' must be a character string or connection"
"

Any idea which step of the Battenberg function could cause this ?

Many thanks in advance in case you can help me on that. In the meantime I will probably switch to ASCAT, since it is running, although it is way less appropriate for WGS data with subclones... meaning I will be glad if I can switch back to Battenberg later on...

Best regards,
Carine

**Comment by jcesar101** [comment]
Hi Carine,

apologies for not replying earlier and thank you for using Battenberg.

Could you please confirm what R version are you currently using?

Would it be possible to see the parameters you are passing to Battenberg on this failed execution?


Kind regards and thanks again.

**Comment by Ximelele** [comment]
Hi,

i ran to similar error year ago and it was due to invalid file name. In my case the file name contained white space so it triggered this error.

**Comment by jcesar101** [comment]
Hi,

thank you for your input.

It would be really helpful if the scripts used to run Battenberg could be shared, just to confirm if this is a problem with the parameters passed or something else.
