### ISSUE TITLE
chr prefix in dev branch

### ISSUE THREAD

**Issue by Rmulet** [Wedge-lab/battenberg#131]
I have noticed that the following lines from the `getBAFsAndLogRs`, which are commented out in `main`, have been added back to the `dev` branch. As a result, this version fails to run with files that contain the "chr" prefix.

```
# We're no longer stripping out the "chr", which is causing problems
#allele_data[,1] = gsub("chr","",allele_data[,1])
#normal_input_data[,1] = gsub("chr","",normal_input_data[,1])
#input_data[,1] = gsub("chr","",input_data[,1])
```

By the way, this is not a bug per se, but when Battenberg (version 2.2.10) is used with files that have the 'chr' prefix, it is added twice to the name of the output files.

**Comment by jcesar101** [comment]
Related to commit [219e8f8](https://github.com/Wedge-lab/battenberg/commit/219e8f8d94a2e5a8b0041ff006617ca32636bb9c): 
Commenting lines removing chr back in to be compatible with chromosome denominations starting with chr. Only allele count loci are required to have the chr in the chromosome name included for the pipeline to run through
