### ISSUE TITLE
Naming convention in callSubclones function 

### ISSUE THREAD

**Issue by Avramis** [Wedge-lab/battenberg#132]
In script battenberg/R/fitcopynumber.R in lines, the gsub command is used to find a specific string  and replace it accordingly, using the result as the new file name.
262
  write.table(subcloneres, gsub(".txt", "_1.txt", output.file), quote=F, col.names=T, row.names=F, sep="\t")
285
  write.table(subcloneres[,c(1:7,18:67)], gsub(".txt","_alternatives.txt",output.file), quote=F, col.names=T, row.names=F, sep="\t")
351
    cellularity_file = gsub("_subclones.txt", "_purity_ploidy.txt", output.file) # NAP: updated the name of the output file, consistent with new title

However, if the provided output.file does not  include the substrings ".txt" or "_subclones.txt" 
the contents of the subclones file (output.file) file is overwritten with information meant for separated files
This occured to me when I ran the reffit callSubclones script I provided an output file as
/foo1/foo2/barssubclones.txt (a file name without an underscore character before the subclones.txt)
As a result the output.file (subclones file) was popualted with the content meant for purity_ploidy.txt file

I would suggest 
EITHER
1) Make it clear is the apporpriate naming convention of the output.file should be 
or
2) If output file does not contain the specific substrings, then the new file suffix should be added at the end instead of repalce

**Comment by jcesar101** [comment]
Hi Avraam,

thank you for letting us know about this. It's been addressed as part of the improvements included in release 3.0.
