### ISSUE TITLE
Main branch OR wait for `v3.0.0`?

### ISSUE THREAD

**Issue by Faizal-Eeman** [Wedge-lab/battenberg#135]
Is it alright if I can use the current `main` branch or do you recommend sticking to `v2.2.9` until `v3.0.0` is released?

Also, wondering if you have an estimate on when `v3.0.0` will be released?

**Comment by Faizal-Eeman** [comment]
> Is it alright if I can use the current `main` branch

Because there have been a large number of commits with several bug fixes since `v2.2.9`, I'd prefer to use the `main` branch.

**Comment by jcesar101** [comment]
Hi,

thank you for your interest in the Battenberg package.

Although `2.2.10` is the last stable release, you can also use the version in the `dev` branch for most scenarios, which (as you mentioned) it also includes additional functionality and bug corrections. Please try it and let us know if you have any problems  with that version.

Our objective is to complete the new release before the end of the year, but we will keep you updated through this repo.

**Comment by Faizal-Eeman** [comment]
@jcesar101 Thanks for the info!

**Comment by Faizal-Eeman** [comment]
> you can also use the version in the `dev` branch for most scenarios

@jcesar101 For immediate, fixable solutions, should we create pull requests to the `dev` branch?

**Comment by jcesar101** [comment]
Hi,

as we are in the process of generating the new release it would be better to raise an issue for any bug detected, so we can check if it's already considered for the release or not. Thank you.

**Comment by Faizal-Eeman** [comment]
Sounds good, thanks!

**Comment by Faizal-Eeman** [comment]
@jcesar101 
We're in the process of updating our [docker-Battenberg](https://github.com/uclahs-cds/docker-Battenberg) and are considering using the `dev` branch as a base. To ensure stability and access to the latest features, we were wondering if it might be possible to create a [release candidate](https://semver.org/#spec-item-9), `v3.0.0-rc.1`, based on your latest developments. This would allow us to test the latest features while also providing a more stable foundation for our Docker image while we await the official `v3.0.0` release.

**Comment by jcesar101** [comment]
Hi,

we are using a slightly different notation, but the pre-release 3.0 version of Battenberg is available at the pre_3.0 branch. This version contains almost all the changes to be included in 3.0 except some changes for the ChrX functionality and the improved documentation.
