### ISSUE TITLE
battenberg is not installed via R devtools. 

### ISSUE THREAD

**Issue by sanghoonleeeins** [Wedge-lab/battenberg#140]
Hi, 

I tried to install battenberg through R devtools. I didn't get an error while installing, but loading the library doesn't work, which means installation is failed. Please see below. I used R 4.4.1. 

I suspect "Skipping 1 packages not available: VariantAnnotation" has a problem but some people say it was okay.  I confirmed that VariantAnnotation v1.50 is installed already. (session information below)

Could you give me any advice? 

##########################################################################
**> devtools::install_github("Wedge-lab/battenberg", force=TRUE)**
Downloading GitHub repo Wedge-lab/battenberg@HEAD
**Skipping 1 packages not available: VariantAnnotation**
── R CMD build ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/3t/dr5hjr912d5468hqh338rf_hg9q0p2/T/RtmpNTcxkB/remotes89f1372083e0/Wedge-lab-battenberg-f4214de/DESCRIPTION’ ...
─  preparing ‘Battenberg’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘Battenberg_2.2.10.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'
   
* installing *source* package ‘Battenberg’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (Battenberg)
> library(battenberg)
**Error in library(battenberg) : there is no package called ‘battenberg’**
> 

###################################################################

**> sessionInfo()
R version 4.4.1 (2024-06-14)**
Platform: aarch64-apple-darwin20
Running under: macOS Sonoma 14.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/New_York
tzcode source: internal

attached base packages:
 [1] stats4    parallel  splines   stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ASCAT_3.2.0                 **VariantAnnotation_1.50.0**    Rsamtools_2.20.0            Biostrings_2.72.1           XVector_0.44.0              SummarizedExperiment_1.34.0
 [7] Biobase_2.64.0              GenomicRanges_1.56.2        GenomeInfoDb_1.40.1         IRanges_2.38.1              S4Vectors_0.42.1            MatrixGenerics_1.16.0      
[13] matrixStats_1.4.1           copynumber_1.29.0.9000      BiocGenerics_0.50.0         gtools_3.9.5                gridExtra_2.3               RColorBrewer_1.1-3         
[19] ggplot2_3.5.1               readr_2.1.5

**Comment by jcesar101** [comment]
Hi, and thank you so much for your interest in Battenberg.

Looks like the installation was fine, could you please try loading the library with capital 'B' at the beginning to see if that works:

`library(Battenberg)`

**Comment by sanghoonleeeins** [comment]
Oh, it is with capital 'B.'   Now it worked.  It is interesting that the github page address is a lower letter but package library is a capital. Thank you for your quick response!
