### ISSUE TITLE
Changing max_rho from 1 to 0.9 will break ascat.plotSunrise()

### ISSUE THREAD

**Issue by TakaYamaguchi** [Wedge-lab/battenberg#38]
Hi,

As sometimes purity seems to be overestimated, I tried max_rho = 0.9 but it caused the issue below.

Error in axis(2, at = seq(0, 1/purity_max, by = 1/3/purity_max), labels = seq(purity_min,  : 
  'at' and 'labels' lengths differ, 4 != 3
Calls: fit.copy.number -> runASCAT -> <Anonymous> -> axis

I'm currently testing min_rho = 0, which may fix the issue but I think the axis labels should handle different min max rho values...?

Thanks,

Taka

**Comment by TakaYamaguchi** [comment]
Just letting you know that setting min-rho = 0, max-rho = 0.9 didn't help..

**Comment by TakaYamaguchi** [comment]
Hi,
The program worked fine when the Sunrise plot was commented out in clonal_ascat.R
Line1432 - ASCAT::ascat.plotSunrise

**Comment by foreverwander** [comment]
T_T im running into the same issue. Also setting min_ploidy and max_ploidy to force WGD breaks the sunrise plotting.

`axis(1, at = seq(0, 1, by = 1/(ploidy_max-1)), labels = seq(ploidy_min, ploidy_max, by = 1))
`

For example ploidy_max = 4.8 and ploidy_min = 2.9 will result in "by" having length of 4 and "labels" having length of 2...

**Comment by foreverwander** [comment]
For my own record, to update the Battenberg:::runASCAT() function in the docker without having to rebuild the package and the docker, I did

Create a /mnt/scripts/runASCAT_hack.R, with
`runASCAT.battenberg.nosunrise <- function(...) { ... #ASCAT::ascat.plotSunrise ...}`

When running Battenberg
```
library(Battenberg)
source('/mnt/scripts/runASCAT_hack.R')
environment(runASCAT.battenberg.nosunrise) <- asNamespace('Battenberg')
assignInNamespace("runASCAT", runASCAT.battenberg.nosunrise, ns = 'Battenberg', envir=as.environment('package:Battenberg'))
```

**Comment by jcesar101** [comment]
Apologies for not replying before. Although this problem is not directly related to Battenberg, and that it currently doesn't allow the user to modify the max_rho value (only programatically), we have tested this scenario and it's working fine with max_rho different from 1.0.
