### ISSUE TITLE
reference files for GRCh38

### ISSUE THREAD

**Issue by jazberna1** [Wedge-lab/battenberg#43]
Hello,

I was wondering if there is a Battenberg reference area for GRCh38, or a procedure to generate the relevant files.

Many thanks
Jorge

**Comment by davidwedge** [comment]
Hi Jorge. These may be obtained from https://www.dropbox.com/sh/bize1n830t0mgzb/AACuzQiHbjQGqIuTJC3Xahzda?dl=0
