### ISSUE TITLE
Reference files - GRCh38 and hg19

### ISSUE THREAD

**Issue by aleksicmil** [Wedge-lab/battenberg#45]
Hi, 

I was wondering whether it is possible to use Battenberg with hg19 or GRCh38? Do you provide reference file bundle?

Thanks

**Comment by jazberna1** [comment]
Hi,

To get the reference files for GRCh37 visit:
https://github.com/Wedge-Oxford/battenberg#required-reference-files

I don't think there is support for GRCh38 yet.

Jorge

**Comment by rdmorin** [comment]
Is anyone looking into resolving this? If not, could one of the developers comment on what would be involved in creating these references for hg38/GRCh38?

**Comment by pawel125** [comment]
It would be great to adapt battenberg to use with hg38...

**Comment by ShaiberAlon** [comment]
Thanks for developing this tool and providing it to the community!
Any update on reference files for hg38? I see that this path exists on the ORA: https://ora.ox.ac.uk/objects/uuid:08e24957-7e76-438a-bd38-66c48008cf52

But it does not seem to include any files for now.

**Comment by davidwedge** [comment]
Due to COVID-19, the ORA are not currently able to upload large files to the public repositories. However, the hg38 Battenberg reference files may be obtained from Dropbox:
[https://www.dropbox.com/sh/bize1n830t0mgzb/AACuzQiHbjQGqIuTJC3Xahzda?dl=0]

**Comment by ShaiberAlon** [comment]
Thank you very much for the quick response David!

**Comment by davidwedge** [comment]
I would like to correct my last comment. The references are from today available from ORA:
[](https://ora.ox.ac.uk/objects/uuid:08e24957-7e76-438a-bd38-66c48008cf52)

**Comment by davidwedge** [comment]
https://ora.ox.ac.uk/objects/uuid:08e24957-7e76-438a-bd38-66c48008cf52
