### ISSUE TITLE
number of 'X' in sunrise plot and their correspondence to subclones.txt file

### ISSUE THREAD

**Issue by jazberna1** [Wedge-lab/battenberg#49]
Hello,

I have done different Battenberg runs where I get either one or two 'X' in the sunrise plot. I was wondering if you could help me to understand how the number of 'X' links to the solutions in the subclones.txt.

Specifically I have two questions, any advice on those will be much appreciated.

1. Please correct me if I am wrong. My understanding is that a sunrise plot with a single 'X' means that there is a single tumour cell population. Then a sunrise plot with two 'X' means that there are two tumour cell populations corresponding to two states of any of the possible solutions in the subclones.txt file.

2. I see however that even if there is a single 'X' in the sunrise plot the solutions in the  subclones.txt include two states. Does this mean that one of the stages is negligible?

I have attached a png file showing two sunrise plots with one and two 'X'. In the plot with a single 'X' I am also showing the two states of solution A.
<img width="922" alt="Screenshot 2020-04-10 at 10 55 45" src="https://user-images.githubusercontent.com/27732589/78978332-dd92b680-7b19-11ea-8ae3-dbe5c50e74e7.png">

Many thanks
Jorge

**Comment by jcesar101** [comment]
Hi,

apologies for this late reply. We tried to repeat this behaviour using different types of samples but we couldn't. Would it be possible to get more information about the samples and running conditions that derived on having two Xs in the sunrise plot? That would be greatly appreciated.
