### ISSUE TITLE
interpretation of [samplename]_subclones_chr*.png files

### ISSUE THREAD

**Issue by jazberna1** [Wedge-lab/battenberg#50]
Hello,

This question is regarding the [samplename]_subclones_chr*.png. Is it the BAF what those plots are showing?

Many thanks
Jorge

**Comment by davidwedge** [comment]
The upper subfigure shows logR and the lower figure shows BAF. Both figures show the values for individual SNPs as grey dots and the bottom figure also shows the average value of the BAF within each segment (green line for clonal segments, red line for subclonal segments)

**Comment by jazberna1** [comment]
Hello Dave,

Thanks so much for the explanation!
Jorge
