### ISSUE TITLE
Difference between the sum of copy number segments and ntot values.

### ISSUE THREAD

**Issue by Sames-Jtudd** [Wedge-lab/battenberg#52]
Hi, 
I hope you can help me to understand the output from battenberg. 
In the output of the call subclones part of the pipline a "segmentation file" is produced. This file has the clonal / subclonal copy number for each segment in the genome. 
Here is a section that deomonstrates my confusion 

chr          startpos               endpos BAF        pval        LogR      ntot       nMaj1_A             nMin1_A             frac1_A

21           5066290                5377969                0.534632035       0.203264531       0.073106415       2.109409229       1              1                1

21           5379291                13227129             0.790123457       0.090253745       0.064570678       2.096525116       2              1                1

21           13227353             46672988             0.5          1              0.004959692       2.008640488       1              1              1

 Put most simply for regions with no called clonality (eg row 2) why is the sum of the major and minor alleles not equal to ntot. What does the ntot represent?  How should there differences be reconciled?

many thanks

**Comment by davidwedge** [comment]
Hi Jamie,
The ntot values are estimated using both BAF and logR. However, these are generally less accurate than the values reported in the nMaj1_A and nMin1_A columns since the latter depend on phased BAF values only and are therefore unaffected by noisy logR values. I advise you to use the nMaj and nMin values rather than ntot.
David

**Comment by Sames-Jtudd** [comment]
thanks, david
