### ISSUE TITLE
Unable to download Reference files GRCh37

### ISSUE THREAD

**Issue by Rashesh7** [Wedge-lab/battenberg#57]
Hello,

I am unable to download a few files from https://ora.ox.ac.uk/objects/uuid:2c1fec09-a504-49ab-9ce9-3f17bac531bc 
for example battenberg_wgs_replic_correction_1000g_v3.tar.gz. 
Is there another way to access these files?

Many Thanks,
Rashesh

**Comment by davidwedge** [comment]
Hi Rashesh. This file should be downloadable from ORA. Is this this still problematic or can I close this issue?

**Comment by Rashesh7** [comment]
Hi David,

Please go ahead and close the issue. I was able to run this with the files you had provided.

Sorry for not updating earlier.

Many Thanks,
Rashesh
