### ISSUE TITLE
Incorrect variable name in prepare_wgs.R

### ISSUE THREAD

**Issue by jykr** [Wedge-lab/battenberg#58]
Hi, 

Thanks for the great package.
I was keep having the error saying "subscript out of bounds" while running `prepare_wgs -> getBAFsAndLogRs`.
This is the stacktrace:
```
Error in as.matrix(x)[i] : subscript out of bounds
In addition: There were 11 warnings (use warnings() to see them)

Enter a frame number, or 0 to exit

1: source("battenberg_wgs_debug.R")
2: withVisible(eval(ei, envir))
3: eval(ei, envir)
4: eval(ei, envir)
5: battenberg_wgs_debug.R#79: battenberg(tumourname = TUMOURNAME, normalname =
6: prepare_wgs(chrom_names = chrom_names, tumourbam = tumour_data_file, normal
7: getBAFsAndLogRs(tumourAlleleCountsFile.prefix = paste(tumourname, "_alleleF
8: mutant_data[cbind(1:len, allele_data[, 3])]
9: `[.data.frame`(mutant_data, cbind(1:len, allele_data[, 3]))
```
Debugging it showed me that in line 62 of `prepare_wgs.R` had a wrong variable:
`normal_input_data = normal_input_data[chrpos_tumour %in% matched_data,]`
Here, it seems that `chrpos_tumour` needs to be `chrpos_normal` for it to be match in dimensions. 
If it is not written as `chrpos_tumour` on purpose, please fix the error. Thanks!

**Comment by jcesar101** [comment]
Thank you for using Battenberg and for letting us know about this problem. It's fixed in the new 3.0 release.
