### ISSUE TITLE
Run refit using refit_suggestion.txt

### ISSUE THREAD

**Issue by Rashesh7** [Wedge-lab/battenberg#59]
Hello,

I was wondering how to run refit using the refit suggestions generated in the initial run? 

Also what is the difference between the *subclones_1.txt and *subclones.txt outputs.

Many Thanks,
Rashesh

**Comment by graceooh** [comment]
@sdentro It would be really useful to have more documentation on this as I'm having the same issue. Thank you very much!

**Comment by sdentro** [comment]
We will look into this as part of a new vignette. Closing this for #111
