### ISSUE TITLE
Dockerfile fails at instillation of R packages

### ISSUE THREAD

**Issue by pblaney** [Wedge-lab/battenberg#69]
Hello,

In an effort to implement Battenberg into a WGS pipeline that is deployable across various systems, one of the first issues I encountered was the failing build recipe used in the current Dockerfile.
When following the directions in the README, this is the outcome from the build command:

------
$ docker build -t battenberg:2.2.9 .
[+] Building 334.6s (13/21)                                                                                               
 => [internal] load build definition from Dockerfile                                                                 0.0s
 => => transferring dockerfile: 3.58kB                                                                               0.0s
 => [internal] load .dockerignore                                                                                    0.0s
 => => transferring context: 2B                                                                                      0.0s
 => [internal] load metadata for docker.io/library/ubuntu:16.04                                                      1.2s
 => [auth] library/ubuntu:pull token for registry-1.docker.io                                                        0.0s
 => [internal] load build context                                                                                    0.1s
 => => transferring context: 1.43MB                                                                                  0.1s
 => [ 1/16] FROM docker.io/library/ubuntu:16.04@sha256:e74994b7a9ec8e2129cfc6a871f3236940006ed31091de355578492ed140  4.2s
 => => resolve docker.io/library/ubuntu:16.04@sha256:e74994b7a9ec8e2129cfc6a871f3236940006ed31091de355578492ed140a3  0.0s
 => => sha256:0ba7bf18aa406cb7dc372ac732de222b04d1c824ff1705d8900831c3d1361ff5 527B / 527B                           0.2s
 => => sha256:e74994b7a9ec8e2129cfc6a871f3236940006ed31091de355578492ed140a39c 1.42kB / 1.42kB                       0.0s
 => => sha256:edf232ee7dc18c57c063bc83533ef2c03c6dfae55a0124f7d372aed51cd1d9c8 1.15kB / 1.15kB                       0.0s
 => => sha256:8185511cd5ad68f14aee2bac83a449a6eea2be06f0a4715b008cfe19f07a64f7 3.36kB / 3.36kB                       0.0s
 => => sha256:4007a89234b4f56c03e6831dc220550d2e5fba935d9f5f5bcea64857ac4f4888 45.96MB / 45.96MB                     1.2s
 => => sha256:5dfa26c6b9c9d1ccbcb1eaa65befa376805d9324174ac580ca76fdedc3575f54 852B / 852B                           0.3s
 => => sha256:4c6ec688ebe374ea7d89ce967576d221a177ebd2c02ca9f053197f954102e30b 169B / 169B                           0.3s
 => => extracting sha256:4007a89234b4f56c03e6831dc220550d2e5fba935d9f5f5bcea64857ac4f4888                            2.2s
 => => extracting sha256:5dfa26c6b9c9d1ccbcb1eaa65befa376805d9324174ac580ca76fdedc3575f54                            0.0s
 => => extracting sha256:0ba7bf18aa406cb7dc372ac732de222b04d1c824ff1705d8900831c3d1361ff5                            0.0s
 => => extracting sha256:4c6ec688ebe374ea7d89ce967576d221a177ebd2c02ca9f053197f954102e30b                            0.0s
 => [ 2/16] RUN apt-get update && apt-get install -y libxml2 libxml2-dev libcurl4-gnutls-dev r-cran-rgl git libssl  60.3s
 => [ 3/16] RUN mkdir /tmp/downloads                                                                                 0.3s 
 => [ 4/16] RUN curl -sSL -o tmp.tar.gz --retry 10 https://github.com/samtools/htslib/archive/1.7.tar.gz &&     mk  33.9s 
 => [ 5/16] RUN curl -sSL -o tmp.tar.gz --retry 10 https://github.com/cancerit/alleleCount/archive/v4.0.0.tar.gz &&  1.7s 
 => [ 6/16] RUN curl -sSL -o tmp.tar.gz --retry 10 https://mathgen.stats.ox.ac.uk/impute/impute_v2.3.2_x86_64_stati  4.1s 
 => [ 7/16] RUN R -q -e 'source("http://bioconductor.org/biocLite.R"); biocLite(c("gtools", "optparse", "devtools  228.1s 
 => ERROR [ 8/16] RUN R -q -e 'devtools::install_github("Crick-CancerGenomics/ascat/ASCAT")'                         0.6s 
 > [ 8/16] RUN R -q -e 'devtools::install_github("Crick-CancerGenomics/ascat/ASCAT")':                                    
#12 0.546 > devtools::install_github("Crick-CancerGenomics/ascat/ASCAT")                                                  
#12 0.547 Error in loadNamespace(name) : there is no package called 'devtools'                                            
#12 0.547 Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>                                            
#12 0.547 Execution halted
executor failed running [/bin/sh -c R -q -e 'devtools::install_github("Crick-CancerGenomics/ascat/ASCAT")']: exit code: 1
------

After troubleshooting, the issue is the R packages to be installed via Bioconductor fail. I believe this is due to the base R version that comes with the Ubuntu 16.04 base image is too far out of date for some of the packages and their internal dependencies.
I have attached an edited version of the Dockerfile that has a successful build recipe (NOTE: the file was given a '.txt' extension for uploading purposes and to be used this extension must be removed). The changes being updating the OS base image to Ubuntu 20.04 and using Bioconductor's BiocManager installation method.
Also, I think it should be clearly stated that this build does not work with any hg38 aligned data or the newly provided hg38 reference data. This will be brought up in subsequent issues.

[Dockerfile.txt](https://github.com/Wedge-lab/battenberg/files/6166690/Dockerfile.txt)

Docker Engine specs:

------

$ docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

------

**Comment by sdentro** [comment]
Thank you for reporting this issue. Changes that fixed it on our end have just been pushed to the branch referenced right below. Would you be willing to try this out and tell us if this works for you?

https://github.com/Wedge-lab/battenberg/tree/fix_dockerfile_master

**Comment by pblaney** [comment]
@sdentro 

So it appears that the build recipe completes correctly but when running the container interactively to test if the `battenberg_wgs.R` script runs correctly, I was given an error that the Battenberg package was not installed.
I inspected the `/usr/local/lib/R/site-library/` directory and confirmed that there is no Battenberg directory.

The workaround I tested and confirmed on my end was to replace line 39 of the Dockerfile with:
`RUN R -q -e 'devtools::install_github("Wedge-Oxford/battenberg")'`

The build recipe completes successfully and the Battenberg package is correctly installed/available.

**Comment by shashkat** [comment]
> @sdentro
> 
> So it appears that the build recipe completes correctly but when running the container interactively to test if the `battenberg_wgs.R` script runs correctly, I was given an error that the Battenberg package was not installed. I inspected the `/usr/local/lib/R/site-library/` directory and confirmed that there is no Battenberg directory.
> 
> The workaround I tested and confirmed on my end was to replace line 39 of the Dockerfile with: `RUN R -q -e 'devtools::install_github("Wedge-Oxford/battenberg")'`
> 
> The build recipe completes successfully and the Battenberg package is correctly installed/available.

Hello @pblaney, I received a similar error (devtools not installed, even though I have it installed, but somehow upon building the dockerfile, it is not able to find it). 

I get upon trying to install devtools:
package(s) not installed when version(s) same as current; use `force = TRUE` to
  re-install: 'devtools' 'splines' 'readr' 'doParallel' 'ggplot2'
  'RColorBrewer' 'gridExtra' 'gtools' 'parallel'

I tried your solution, but there is still no change. Any help would be appreciated. The error is:

 => ERROR [ 8/16] RUN R -q -e 'devtools::install_github("Wedge-Oxford/battenberg")'                                                                                                                    0.3s
------
 > [ 8/16] RUN R -q -e 'devtools::install_github("Wedge-Oxford/battenberg")':
#11 0.314 > devtools::install_github("Wedge-Oxford/battenberg")
#11 0.315 Error in loadNamespace(name) : there is no package called 'devtools'
#11 0.315 Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
#11 0.315 Execution halted
------
executor failed running [/bin/sh -c R -q -e 'devtools::install_github("Wedge-Oxford/battenberg")']: exit code: 1

**Comment by pblaney** [comment]
Hi  Shashank @shashkat,

Which Dockerfile are you using to build the image? I believe the version that is part of the master branch was not updated after this issue was addressed by Stefan.
He created the https://github.com/Wedge-lab/battenberg/blob/fix_dockerfile_master/Dockerfile to address the issue I raised originally.

Let me know if you still have an issue.
Best,
Patrick

**Comment by sdentro** [comment]
Docker support will be dropped from the next version. Closing this ticket
