### ISSUE TITLE
Issues with hg38 aligned BAMs and new hg38 reference data

### ISSUE THREAD

**Issue by pblaney** [Wedge-lab/battenberg#70]
Hello,

With the recent release of the hg38 reference data, I have been working to run Battenberg with my hg38 aligned BAM files but have run into multiple issues so I wanted to make others aware.

First, I recommend those using looking to use the hg38 reference data to download them from the Dropbox site https://www.dropbox.com/sh/bize1n830t0mgzb/AACuzQiHbjQGqIuTJC3Xahzda?dl=0 instead of the ORA site as  there seemed to be an issue with completing the download of the `beagle5.zip`. Also, the ORA site is completely missing the `shapeit2` files that are used in the `impute_info.txt` file. Lastly for this point, the README.txt for the reference data is incomplete (there needs to be symlinks for the chrX files in the `1000G_loci_hg38` directory)

Second, the current version of the `master` branch (which is the default branch for those cloning the repo) does not support the new hg38 reference data. The `hg38_ChrNotation_fix_NAP` branch has implemented a fix for working with the hg38 reference data that will allow you to get past the first step (the `prepare_wgs` function call in the `battenberg.R` script) correctly.

Third, when using the `hg38_ChrNotation_fix_NAP` branch,  the `battenberg_wgs.R` script requires extensive rewriting of default variables for compatibility with the hg38 reference data. The "..../" is used here as a placeholder for some user defined parent directory. The second half of the variables are specific for the use of Beagle5. Important notes for this part include: running Beagle5 requires Java 8, the JAR executable file must be downloaded https://faculty.washington.edu/browning/beagle/b5_0.html, all the reference files downloaded from the `beagle5.zip` need to moved into a new subdirectory that matches the GENOME_VERSION string (i.e. `..../beagle5/b38`), and the JAR file must be in the `..../beagle5` directory.

----------

IMPUTEINFOFILE = "..../imputation/impute_info.txt"
G1000PREFIX = "..../1000G_loci_hg38/1kg.phase3.v5a_GRCh38nounref_allele_index_chr"
G1000PREFIX_AC = "..../1000G_loci_hg38/1kg.phase3.v5a_GRCh38nounref_loci_chrstring_chr"
GCCORRECTPREFIX = "..../GC_correction_hg38/1000G_GC_chr"
REPLICCORRECTPREFIX = "..../RT_correction_hg38/1000G_RT_chr"
PROBLEMLOCI = "..../probloci.txt.gz"

GENOME_VERSION = "b38"
BEAGLE_BASEDIR = "..../beagle5"
BEAGLEJAR = file.path(BEAGLE_BASEDIR, "beagle.12Jul19.0df.jar")
BEAGLEREF.template = file.path(BEAGLE_BASEDIR, GENOME_VERSION, "chrCHROMNAME.1kg.phase3.v5a_GRCh38nounref.vcf.gz")
BEAGLEPLINK.template = file.path(BEAGLE_BASEDIR, GENOME_VERSION, "plink.chrCHROMNAME.GRCh38.map")

----------

Fourth, there is a hardcoded variable in the `battenberg` function within the `battenberg.R` called "GENOMEBUILD" which is set to "hg19". This must be edited in place to "hg38".

Finally, even after all this, I have still been unsuccessful in having the pipeline execute 100% properly. I will detail the current issue in a new thread. I am grateful that the developers have produced the hg38 reference files, I just wish there also would have been a warning that they aren't fully ready for use in the current version of the software.

**Comment by jcesar101** [comment]
Hi,

apologies for replying until now. There is a new version of Battenberg available at the DEV branch from our repository. The datasets at [ORA](https://ora.ox.ac.uk/objects/uuid:08e24957-7e76-438a-bd38-66c48008cf52) for hg38 have also been updated. Please let us know if there are still problems and we can raise a new issue to address them.
