### ISSUE TITLE
Error in write_battenberg_phasing function

### ISSUE THREAD

**Issue by pblaney** [Wedge-lab/battenberg#71]
Hello,

While attempting to run hg38 aligned BAMs through Battenberg (`hg38_ChrNotation_fix_NAP` branch) using the hg38 reference data. I encountered an error that stems from the `write_battenberg_phasing` function which halted execution. The log file which I've attached dictates the following:

----------

Error in fix.by(by.y, y) : 'by' must specify a uniquely valid column
Calls: battenberg ... write_battenberg_phasing -> merge -> merge.data.frame -> fix.by

---------

To try and troubleshoot the problem, I worked through the possible lines that could be the cause.
The bafsegmented_file as well as all SNPfiles and imputedHaplotypeFiles exist and are appear to be populated correctly. 
And what makes things more confusing is that the output VCF files from this function all seem to have been produced (filename convention - [tumorname]_Battenberg_phased_[chrom].vcf) and are populated.

[battenberg_output.log](https://github.com/Wedge-lab/battenberg/files/6173187/battenberg_output.log)

**Comment by pblaney** [comment]
Hello @pawel125,
Unfortunately, I've abandoned my efforts to get a working version as the developers appear to be making the changes for Battenberg to work on hg38 aligned BAMs with the appropriate reference data. However, I am not sure when this release is expected. I too will am waiting patiently for this.

Patrick

**Comment by pawel125** [comment]
There are the reference files for hg38 already available, I am working with this assembly. I have found that the error occured for chromosome chrX in write_battenberg_phasing() function, when calling the merge function. I excluded chrX from impute_info.txt to skip that chromosome and it worked. It's not a perfect solution, and write_battenberg_phasing() probably can easily be fixed.

**Comment by pblaney** [comment]
Ah, this is good to know. Also, it appears there is a fix for that as well but hasn't been incorporated to the `dev` branch if you look at the pull requests. Perhaps this means that v3 will be out soon.

**Comment by pawel125** [comment]
I hope so!
