### ISSUE TITLE
The beagle5.zip in Battenberg reference (hg38) doesn't work.

### ISSUE THREAD

**Issue by xysj1989** [Wedge-lab/battenberg#73]
Hello Naser,

This is Jian. When I try to download Battenberg reference (hg38) from the following link: https://ora.ox.ac.uk/objects/uuid:08e24957-7e76-438a-bd38-66c48008cf52 . I found that beagle5.zip cannot be compressed. Did you have this problem?

Thank you.

**Comment by Lucpen** [comment]
Hello, 
I had the same problem and saw that @pblaney opened issue #70 about it (https://github.com/Wedge-lab/battenberg/issues/70). He said you could download from here:
https://www.dropbox.com/sh/bize1n830t0mgzb/AACuzQiHbjQGqIuTJC3Xahzda?dl=0

**Comment by jcesar101** [comment]
Hi,

apologies for replying until now. There is a new version of Battenberg available at the DEV branch from our repository. The datasets at [ORA](https://ora.ox.ac.uk/objects/uuid:08e24957-7e76-438a-bd38-66c48008cf52) for hg38 have also been updated. Please let us know if there are still problems and we can raise a new issue to address them.
