### ISSUE TITLE
Issues with running battenberg with hg38

### ISSUE THREAD

**Issue by Lucpen** [Wedge-lab/battenberg#74]
Hello,

I have been trying to run Battenberg with hg38 and have been unable to do so with the master branch. I was looking through the comments and saw that a couple of months ago @pblaney recommended hg38_ChrNotation_fix_NAP  but he still had issues.
Is there a stable version for hg38? What branch should I clone?

**Comment by jcesar101** [comment]
Hi,

apologies for replying until now. There is a new version of Battenberg available at the DEV branch from our repository. The datasets at [ORA](https://ora.ox.ac.uk/objects/uuid:08e24957-7e76-438a-bd38-66c48008cf52) for hg38 have also been updated. Please let us know if there are still problems and we can raise a new issue to address them.
