### ISSUE TITLE
Error in callChrXsubclones function

### ISSUE THREAD

**Issue by anderdnavarro** [Wedge-lab/battenberg#77]
Hello,

I'm running Battenberg for hg19 with a case that doesn't seem to contain any copy number alteration. However, I'm not be able to complete the analysis because of the following error: `Error in { : task 1 failed - "missing value where TRUE/FALSE needed" `.

I tracked the error to the `callChrXsubclones` function. I'll try to explain the reason and the two possible solutions I've thought of, but I don't know if they are correct or maybe something else needs to be changed:

- In my case, `nrow(BBloh) = 1` in line 62
- So, it enters in the if statement of line 64, but `BBloh` remains 1
- In line 77 `seg$type = "loss"` according to `seg$mean` and in line 84 `seg$CNA = "yes"`

Up to this point, the declaration of the variables seems to be correct.

- Because of `seg$CNA = "yes"`, it enters in the if statement of line 87, where the problem appears in line 126. The code of this part is:

> else if (seg$type == "loss") {
>         seg$CN = 0
>         if (nrow(BBloh) > 0) {
>             seg$clonal = ifelse(round(abs(explogrLoss -  seg$mean), digits = 2) < round(abs(sd(BBloh$LogR)/explogrLoss), digits = 2), "yes", "no")
>         }
>         else if (nrow(BBloh) == 0) {
>            seg$clonal = ifelse(round(abs(explogrLoss - seg$mean), digits = 2) < round(abs(BBsd_max/explogrLoss), digits = 2), "yes", "no")
>         }
>       }

- As nrow(BBloh) = 1, it enters in the first `if`, but when the function tries to calculate the `sd(BBloh$LogR)`, it returns `seg$clonal = NA` because there is only one number in the variable.
- Because this reason, in line 173 `if (seg$clonal == "no")`, the above error appears and the program finishes incomplete.

The solutions I propose are:

1. In line 126: Change `if (nrow(BBloh) > 0)` by `if (nrow(BBloh) > 1)` and in line 131 `else if (nrow(BBloh) == 0)`by `else if (nrow(BBloh) <= 1)`. So you don't have to calculate the sd of just one number.
2. Or change lines 80 and 84 so `if (nrow(BBloh) == 1){seg$CNA == "no"}`. Thus, it enters in the else statement of line 138 without errors.

My BBloh looks like:
```
   chr startpos   endpos       BAF      pval        LogR     ntot
10   9 44891284 44900981 0.7768091 0.5352291 -0.05235313 1.919503
   nMaj1_A nMin1_A frac1_A nMaj2_A nMin2_A frac2_A SDfrac_A
10       1       0       1      NA      NA      NA       NA
   SDfrac_A_BS frac1_A_0.025 frac1_A_0.975
10          NA            NA            NA
```
And SAMPLEsegs:
```
   sampleID chrom arm start.pos   end.pos n.probes    mean
1 2102635TD     X   p   2600150  58563072   375739 -0.1034
2 2102635TD     X   q  61690452 155255094   636530 -0.1074
```

It is very likely that the error occurred because the case doesn't have a CNA, however I believe that this situation should be contemplated (or at least given a proper error).

**Comment by nansari-pour** [comment]
Thank you for bringing this to our attention. I agree with your first fix, the logic of which is already used to expand BBloh when nrow<=1. The fix will be added as part of the Battenberg update very soon.
