### ISSUE TITLE
Can I skip some code to get only 2 output files?

### ISSUE THREAD

**Issue by NaamaGilad** [Wedge-lab/battenberg#78]
Hello,

I am running Battenberg to get these two outputs:
[samplename]_subclones.txt, [samplename]_rho_and_psi.txt

Is there a way to skip some of the code to speed things up and get only these outputs?
Currently one run takes 5 hours or more.

Thanks,
Naama

**Comment by davidwedge** [comment]
Hi Naama,
I'm afraid not. The whole pipeline needs to run to produce these outputs. Although Battenberg can be run on a single processor, we advise running on an HPC if possible to reduce the runtime.
David

**Comment by NaamaGilad** [comment]
Thank you very much for the answer.

I am using 4 processes per sample, but running multiple samples in parallel, so the resources are limited.
How would you suggest to run the procedure for large cohorts?

Thanks,
Naama
