### ISSUE TITLE
Empty reference file shapeit2 chrX_nonPAR

### ISSUE THREAD

**Issue by kateeasoncrukci** [Wedge-lab/battenberg#79]
Hi there,

The reference file `ALL.v1a.shapeit2_integrated_chrX_nonPAR.GRCh38.20181129.phased.hap.gz` provided [here](https://www.dropbox.com/sh/bize1n830t0mgzb/AAAbmJCGL04zOqNm7v7HRfjza/shapeit2?dl=0&preview=ALL.v1a.shapeit2_integrated_chrX_nonPAR.GRCh38.20181129.phased.hap.gz) appears to be empty.

This caused an error in `impute2`, which did not get picked up by Battenberg:

`ERROR: There are no type 2 SNPs after applying the command-line settings for this run, which makes it impossible to perform imputation. One possible reason is that you have specified an analysis interval (-int) that contains reference panel SNPs but not inference panel SNPs -- e.g., this can happen at the ends of chromosomes. Another possibility is that your genotypes and the reference panel are mapped to different genome builds, which can lead the same SNPs to be assigned different positions in different panels. If you need help fixing this error, please contact the authors.`

and so the CN profiles generated had a large chunk of X with no breakpoints across a fairly large cohort of samples.

I assume this file should not be empty, so would it be possible to provide the correct version?

Thanks so much!

**Comment by jcesar101** [comment]
The recommendation, to use this package with hg38 reference files, is to use [beagle](https://faculty.washington.edu/browning/beagle/beagle.html) instead of [impute](https://mathgen.stats.ox.ac.uk/impute/impute_v2.html) for phasing, following the instructions provided [here](https://github.com/Wedge-lab/battenberg/tree/v2.2.10#hg38-for-beagle5).

Validation is still in progress and we will update this issue accordingly as soon as the tests have been completed.

**Comment by jcesar101** [comment]
An updated set of reference files for hg38 (including Beagle, Impute and with and wthout the "chr" prefix on the chromosome name) were uploaded to the [ORA](https://ora.ox.ac.uk/objects/uuid:08e24957-7e76-438a-bd38-66c48008cf52) repository. This dataset was already validated locally but further tests with different samples and processing environments are still in progress.

**Comment by jcesar101** [comment]
Hi,

there is a new version of Battenberg available at the DEV branch from our repository. The datasets at [ORA](https://ora.ox.ac.uk/objects/uuid:08e24957-7e76-438a-bd38-66c48008cf52) for hg38 have also been recently updated. Please let us know if there are still problems and we can raise a new issue to address them.
