### ISSUE TITLE
Can Battenberg be used with ASCATngs output?

### ISSUE THREAD

**Issue by hannanw** [Wedge-lab/battenberg#81]
Hi,

Is it possible to run the battenberg pipeline over ASCAT or ASCATngs output? For example I have the allele counts for both the tumor and the normal sample from ASCATngs, could I just feed it in to the `battenberg` function and run the pipeline from there?

I tried doing so, with the code below but I get an error message telling me that the `unused argument (normal_name = "MCF10A")`. When I remove the `normal_name` parameter, it fails and gives this error `Error in prepare_wgs(chrom_names = chrom_names, tumourbam = tumour_data_file,  : 
  argument "normalname" is missing, with no default`. I tried feeding the battenberg function `analysis = "cell_line"`, but I get the error  `unused argument (analysis= "cell_line")`. 

Any help would be greatly appreciated, thanks!

Code to try and run battenberg pipeline:
`battenberg(tumourname= 'H_LS-BH-A208-01A-11D-A159-09', 
        tumour_data_file = '~/tmpAscat/ascat/H_LS-BH-A208-01A-11D-A159-09_alleleCounts.tab',
        normal_name ='MCF10A',
        normal_data_file = '~/tmpAscat/ascat/MCF10A_0_EDHG200003860-1a_H2L5YDSXY_L3.count' ,
        ismale=FALSE, 
        imputeinfofile='~/battenberg/reference/hg38/imputation/impute_info.txt', 
        g1000prefix='~/battenberg/reference/hg38/1000G_loci/1kg.phase3.v5a_GRCh38nounref_loci_chr', 
      g1000allelesprefix='~/battenberg/reference/hg38/1000G_loci/1kg.phase3.v5a_GRCh38nounref_allele_index_chr', 
        gccorrectprefix='~/battenberg/reference/hg38/GC_correction/1000G_GC_chr', 
        repliccorrectprefix='~/battenberg/reference/hg38/replicationtimings/1000G_RT_chr', 
        problemloci='~/battenberg/reference/hg38/problem_loci/probloci.txt.gz', 
        data_type='WGS',
        skip_allele_counting=T,
        skip_preprocessing=F,
        skip_phasing=F,
        prior_breakpoints_file=NULL)`

Warmest regards,
Hannan

**Comment by jcesar101** [comment]
Hi,

apologies for replying until now. We don't recommend using the output from ASCAT or ASCATngs, particularly if WGS is available. In any case, there is a new version of Battenberg available at the DEV branch in our repository, that includes several updates to the different modes supported. Please let us know if there are still problems and we can raise a new issue to address them.
