### ISSUE TITLE
Missing RT_correction_hg38.zip file.

### ISSUE THREAD

**Issue by pawelqs** [Wedge-lab/battenberg#83]
Hi,

I do not see the RT_correction_hg38.zip file in the https://ora.ox.ac.uk/objects/uuid:08e24957-7e76-438a-bd38-66c48008cf52 directory. I have some older copy of this (downloaded from some Dropbox a year ago). Is it just missing, or is it no longer being used? 

Best wishes,
Paweł

**Comment by jcesar101** [comment]
Hi,

apologies for replying until now. The datasets at [ORA](https://ora.ox.ac.uk/objects/uuid:08e24957-7e76-438a-bd38-66c48008cf52) for hg38 have been recently updated. Please let us know if there are still problems and we can raise a new issue to address them.
