### ISSUE TITLE
installation and example data

### ISSUE THREAD

**Issue by ranjit58** [Wedge-lab/battenberg#89]
Hello friends,
I installed the dev version of Dockerfile 9the master version have installation errors). I am running hg19, paired analysis, USEBEAGLE = FALSE, with chr23 changed as X. I got the same error on HCC1143 and some in-house bam files. The code starts fine but halt after few hours with following error. 

any help is appreciated. 

```
[1] "BAFlen=6"
[1] "BAFlen=6"
[1] "BAFlen=26"
[1] "BAFlen=16"
[1] "BAFlen=120"
Error in `check_names_before_after_character()`:
! Can't find columns `pos`, `ref`, `alt`, `hap1`, `hap2` in `.data`.
Backtrace:
   x
1. \-Battenberg::battenberg(...)
2.   \-Battenberg::write_battenberg_phasing(...)
3.     +-...[]
4.     +-readr:::`[.spec_tbl_df`(...)
5.     +-base::NextMethod(`[`)
6.     \-tibble:::`[.tbl_df`(...)
7.       \-tibble:::check_names_df(j, x)
8.         \-tibble:::check_names_before_after_character(j, names(unclass(x)))
9.           \-rlang::abort(error_unknown_names(unknown_names))
Warning message:
The `path` argument of `write_tsv()` is deprecated as of readr 1.4.0.
Please use the `file` argument instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.
Execution halted
```

**Comment by seedgeorge** [comment]
Hi Ranjit, I'm not a developer for this repository but we [made our own Docker image ](https://hub.docker.com/repository/docker/seedgeorge/battenberg_custom_amd64) - our image is simpler than the official one and doesn't contain any of the reference data files. We are internally using this Docker in a nextflow pipeline and so have a custom script based on the battenberg_wgs.R script that suits our setup. Sorry if this doesn't help much!

**Comment by ranjit58** [comment]
> Hello friends, I installed the dev version of Dockerfile 9the master version have installation errors). I am running hg19, paired analysis, USEBEAGLE = FALSE, with chr23 changed as X. I got the same error on HCC1143 and some in-house bam files. The code starts fine but halt after few hours with following error.
> 
> any help is appreciated.
> 
> ```
> [1] "BAFlen=6"
> [1] "BAFlen=6"
> [1] "BAFlen=26"
> [1] "BAFlen=16"
> [1] "BAFlen=120"
> Error in `check_names_before_after_character()`:
> ! Can't find columns `pos`, `ref`, `alt`, `hap1`, `hap2` in `.data`.
> Backtrace:
>    x
> 1. \-Battenberg::battenberg(...)
> 2.   \-Battenberg::write_battenberg_phasing(...)
> 3.     +-...[]
> 4.     +-readr:::`[.spec_tbl_df`(...)
> 5.     +-base::NextMethod(`[`)
> 6.     \-tibble:::`[.tbl_df`(...)
> 7.       \-tibble:::check_names_df(j, x)
> 8.         \-tibble:::check_names_before_after_character(j, names(unclass(x)))
> 9.           \-rlang::abort(error_unknown_names(unknown_names))
> Warning message:
> The `path` argument of `write_tsv()` is deprecated as of readr 1.4.0.
> Please use the `file` argument instead.
> This warning is displayed once every 8 hours.
> Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.
> Execution halted
> ```

btw, i got it working, when skip writing the phase information to battenberg function as below
write_battenberg_phasing = F
