### ISSUE TITLE
Can battenberg be used in turmor only projects?

### ISSUE THREAD

**Issue by shengqh** [Wedge-lab/battenberg#90]
We have hundreds tumor WGS data (no normal data) and we want to call somatic CNVs. I am wondering if battenberg can do that. Thank you so much.

**Comment by nansari-pour** [comment]
Thank you for your interest in using Battenberg. The tumour-only version is currently under development and is being tested under multiple scenarios. We will make a public announcement here and elsewhere once it is ready. Stay tuned!
