### ISSUE TITLE
Issues with the docker file

### ISSUE THREAD

**Issue by sunhollyjolly** [Wedge-lab/battenberg#94]
Whenever I tried to pull from the Docker in local, I got this error msg regarding R dependencies. 
Error message can be found below. 

=> ERROR [ 8/16] RUN R -q -e 'devtools::install_github("Crick-CancerGenomics/ascat/ASCAT")'                                           0.2s
------
 > [ 8/16] RUN R -q -e 'devtools::install_github("Crick-CancerGenomics/ascat/ASCAT")':
#11 0.233 > devtools::install_github("Crick-CancerGenomics/ascat/ASCAT")
#11 0.233 Error in loadNamespace(name) : there is no package called 'devtools'
#11 0.233 Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
#11 0.234 Execution halted

**Comment by sdentro** [comment]
Docker support will be dropped from the next version. Closing this ticket
