### ISSUE TITLE
potential issue with plotting

### ISSUE THREAD

**Issue by mariya-kazachkova** [Wedge-lab/battenberg#96]
Hello,

I'm running Battenberg on some WGS samples (GRCh38) and am getting some odd sunrise plots. These samples have also been run using ASCAT. When I compare the sunrise plots between Battenberg and ASCAT, the ones coming from Battenberg look very odd (please see images below of the sunrise plots for the same sample run with ASCAT and Battenberg). Notably, the Cancer Cell Fraction distributions using the ASCAT and Battenberg output yield  very similar results, and the purity and ploidy estimates using each pipeline are very similar (see third image). 

I'm using the most recent version of Battenberg and am not changing any of the parameters used for plotting. 

Thanks for your help!
Mariya 

## ASCAT: 
![PCGA-1064-BE-02_T sunrise_ASCAT](https://user-images.githubusercontent.com/95315049/202029136-f7174fe1-6947-4e5d-ac3a-53ddf3c11d56.png)

## Battenberg:
![PCGA-1064-BE-02_tumor_distance_Battenberg](https://user-images.githubusercontent.com/95315049/202029159-5d133f0d-0914-4eb2-b3de-20bb96a1fb03.png)

## Comparison:
![PCGA-1064-BE-02](https://user-images.githubusercontent.com/95315049/202029528-df1159f8-ae0a-4458-8610-22da942f558a.png)

**Comment by jcesar101** [comment]
Hi!

Thank you for letting us know about these differences. As Battenberg also uses ASCAT to generate these sunrise plots, tt could be related to different versions of the package or its dependencies, that cause this different palette in the plots, and given that the results are quite similar (just a difference in the plots color palette), we will be closing this issue as the ASCAT functions are maintained in a different repository.
