### ISSUE TITLE
GRCh38 reference files are corrupt

### ISSUE THREAD

**Issue by peter-yufan-zeng** [Wedge-lab/battenberg#98]
Tried downloading the reference files [on ORA](https://ora.ox.ac.uk/objects/uuid:08e24957-7e76-438a-bd38-66c48008cf52) multiple times on different servers and on personal computer. However, trying to unzip the file throws error:
`error [Battenberg_reference_hg38.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
`

I was able to get most of the files out using `zip -FF -fz Battenberg_reference_hg38.zip --out repaired.zip`. However, fixing the zip files may make use by other user easier.

**Comment by jcesar101** [comment]
Good day Peter,

we have tried downloading and unpacking the files and there weren't any issues so far. Could you please share with us what O.S. platform, zip tool and browser are you using (including versions), to see if we can replicate this problem?

Kind regards and thank you.

**Comment by peter-yufan-zeng** [comment]
I tried again on another local computer and had no problems, but the problem unzipping on my cluster persists, even if I transfer the same downloaded file that I was able to unzip to my cluster.. 

Both uses UnZip 6.00. The computer that I was able to unzip the files successfully uses Ubuntu 20.04.5 LTS while the cluster I am having trouble with uses CentOS Linux 7 (Core).

**Comment by jcesar101** [comment]
Thank you Peter. I see, the problem should probably be platform-specific then. Given that it's a large ZIP file, you may find problems when trying to open/decompress it in 32-bit operating systems, on filesystems that don't handle large files properly, or with older versions of UnZip.

**Comment by peter-yufan-zeng** [comment]
Thank you for your help Julio. I will close the issue now since it's likely platform specific
